#  **Практическое занятие №2. Линейная алгебра.**

### Знакомство с библиотекой **NumPy**

numpy - библиотека для быстрой работы с большими массивами и матрицами

https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np

### Создание массива

In [2]:
# явно указать через список
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)
print()
print(b)

[1 2 3]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# создать нулевой массив заданного размера
a = np.zeros(2)
b = np.zeros((2, 3))
c = np.zeros((2, 2, 3))

print(a)
print()
print(b)
print()
print(c)

[0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
# создать единичный массив заданного размера
a = np.ones(2)
b = np.ones((2, 3))
c = np.ones((2, 2, 3))

print(a)
print()
print(b)
print()
print(c)

[1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]]

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
# создать нулевой или единичный массив такого же размера, как некоторый другой
a = np.array([1, 2, 3])
b = np.zeros_like(a)

print(b)

[0 0 0]


In [6]:
a = np.array([[5, 6], [7, 8]])
b = np.ones_like(a)

print(b)

[[1 1]
 [1 1]]


In [7]:
# создать единичную матрицу (двумерный массив)
a = np.eye(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# создать массив чисел от from до to с шагом step (одномерный массив)
from_ = 1
to_ = 5
step_ = 0.5
a = np.arange(from_, to_, step_)

print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [9]:
# по умолчанию from = 0, step = 1
a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# можно явно указать тип при создании массива вторым аргументов
a = np.zeros((2, 5), 'float')

print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# можно заменить тип 
a = np.array([1, 2, 5])
b = a.astype('str')

print(b)

['1' '2' '5']


In [12]:
# посмотреть все возможные типы
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

**Задача 1**

Создайте вектор длины 20 из случайных целых чисел от -5 до 10. 

Вам пригодится метод https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

In [13]:
a = np.random.randint(-5, 11, 20)
print(a)

[ 3  6  9  2 -4  5  5  7  4 -1  3 -4 10 -2  0 -4  8  9 10  9]


### Доступ к элементам массива, срезы

In [14]:
# доступ по набору целочисленных индексов
a = np.array([[2, 4, 5], [8, 6, 7], [10, 15, 20]])

print(a)
print(a[0][0])
print(a[0, 0])

[[ 2  4  5]
 [ 8  6  7]
 [10 15 20]]
2
2


In [15]:
# срез массива вдоль первой оси
print(a)
print(a[0])
print(a[0, :])

[[ 2  4  5]
 [ 8  6  7]
 [10 15 20]]
[2 4 5]
[2 4 5]


In [16]:
# срез можно делать вдоль любой оси
print(a)
print(a[:, 0])
print(a[:, 1])

[[ 2  4  5]
 [ 8  6  7]
 [10 15 20]]
[ 2  8 10]
[ 4  6 15]


In [17]:
# индексы могут принимать отрицательные значения, отсчет с конца массива
print(a)
print(a[0, -1])
print(a[0, -2])

[[ 2  4  5]
 [ 8  6  7]
 [10 15 20]]
5
4


In [18]:
# срез в виде from, to, step вдоль оси
print(a)
print(a[0:3:2])
print(a[:, 1:3:1])

[[ 2  4  5]
 [ 8  6  7]
 [10 15 20]]
[[ 2  4  5]
 [10 15 20]]
[[ 4  5]
 [ 6  7]
 [15 20]]


In [19]:
# развернуть массив вдоль оси
print(a)
print(a[::-1])
print(a[:, ::-1])

[[ 2  4  5]
 [ 8  6  7]
 [10 15 20]]
[[10 15 20]
 [ 8  6  7]
 [ 2  4  5]]
[[ 5  4  2]
 [ 7  6  8]
 [20 15 10]]


In [20]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
a[::-1]

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

In [22]:
a[:, ::-1]

array([[[3, 4],
        [1, 2]],

       [[7, 8],
        [5, 6]]])

In [70]:
a[:, :, ::-1]

array([[[2, 1],
        [4, 3]],

       [[6, 5],
        [8, 7]]])

**Задача 2**

Напишите функцию, транспонирующую матрицу nxn (без использования соотвествующих методов numpy, можно использовать один цикл)

In [24]:
def custom_transpose(matrix):
    """
    Inputs:
    матрица nхm
    
    Outputs:
    транспонированная матрица
    """
    
    n, m = matrix.shape
    transposed_matrix = np.zeros((m, n), dtype=int)
    for i in range(m):
        transposed_matrix[i] = matrix[:, i]
    
    return transposed_matrix

In [25]:
matrix = np.eye(5)
custom_transpose(matrix)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
matrix = np.array([[[3, 654, 234456, 23445], [34, 54, 765, 23]]])
print(matrix)
#custom_transpose(matrix)

[[[     3    654 234456  23445]
  [    34     54    765     23]]]


In [27]:
matrix.shape[1]

2

**Задача 3**

Cоздайте матрицу 8x8 и заполните ее числами 0 и 1 в шахматном порядке

In [84]:
board= np.zeros((8,8), dtype=int)

board[1::2,::2] = 1
board[::2,1::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Форма массива и ее изменение

In [28]:
# изменить форму
a = np.arange(36)
b = a.reshape(2, 18)
c = a.reshape(4, 9)
d = a.reshape(2, 6, 3)

print('a\n', a)
print('b\n', b)
print('c\n', c)
print('d\n', d)

a
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
b
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]
c
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
d
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [31]:
a = np.array([np.arange(1, 10, 2), np.arange(21, 30, 2)])
a

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29]])

In [32]:
a.reshape(10, )

array([ 1,  3,  5,  7,  9, 21, 23, 25, 27, 29])

In [33]:
a.reshape(5, 2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 21],
       [23, 25],
       [27, 29]])

In [34]:
# узнать форму
print(a.ndim, b.ndim, c.ndim, d.ndim)

print(a.shape, b.shape, c.shape, d.shape)

print(a.size, b.size, c.size, d.size)

2 2 2 3
(2, 5) (2, 3) (4, 9) (2, 6, 3)
10 6 36 36


In [38]:
# важно сохранять размеры при изменении формы
b = np.array([[1, 2, 3], [4, 5, 6]])
c = b.reshape((1, 5))

ValueError: cannot reshape array of size 6 into shape (1,5)

In [40]:
# можно использовать -1, тогда размер вдоль этой оси будет автоматически вычисляться
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape((3, -1))

print(b)

[[1 2]
 [3 4]
 [5 6]]


In [95]:
# развернуть массив в одномерный
a = np.eye(4)
b = a.ravel()

print(a)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]


**Задача 4**

Создайте следующую матрицу, заполненную по "змейке". Используйте срезы и reshape (не вводя значения вручную):

$$\begin{pmatrix} 1 & 2 & 3 & 4 \\ 8 & 7 & 6 & 5 \\ 9 & 10 & 11 & 12 \end{pmatrix}$$

In [97]:
m = np.arange(1, 13).reshape(3, -1)
m[1] = m[1][::-1]
m

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

### Транспонирование матрицы

In [98]:
# краткая запись
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a, a.shape)
print(a.T, a.T.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 4]
 [2 5]
 [3 6]] (3, 2)


In [99]:
# полная запись
a = np.ones((3, 3)) + np.eye(3)

print(a, a.shape)
print(np.transpose(a), np.transpose(a).shape)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]] (3, 3)
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]] (3, 3)


### Математические операции над массивами

Сложение, вычитание, умножение, деление, возведение в степень делаются **поэлементно**

In [100]:
A = np.array([[-1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
B = np.array([[1., -2., -3.], [7., 8., 9.], [4., 5., 6.]])

print(A)
print()
print(B)

[[-1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]

[[ 1. -2. -3.]
 [ 7.  8.  9.]
 [ 4.  5.  6.]]


In [101]:
print(A + B)

[[ 0.  0.  0.]
 [11. 13. 15.]
 [11. 13. 15.]]


In [102]:
print(A - B)

[[-2.  4.  6.]
 [-3. -3. -3.]
 [ 3.  3.  3.]]


In [103]:
print(A * B)

[[-1. -4. -9.]
 [28. 40. 54.]
 [28. 40. 54.]]


In [104]:
print(A / B)

[[-1.         -1.         -1.        ]
 [ 0.57142857  0.625       0.66666667]
 [ 1.75        1.6         1.5       ]]


In [105]:
print(A ** 2)

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


In [106]:
# необязательно формы массивов должны совпадать
# допустимо, чтобы A[i].ndim = B.ndim && A[i].size = B.size
A = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
B = np.array([-1.1, -1.2, -1.3])

print(A[0].ndim, B.ndim)
print(A[0].size, B.size)

1 1
3 3


In [107]:
A * B

array([[ -1.1,  -2.4,  -3.9],
       [ -4.4,  -6. ,  -7.8],
       [ -7.7,  -9.6, -11.7]])

In [108]:
# разумеется, можно умножать массивы на число
A = np.eye(3)

print(3 * A)

[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]


**Задача 5**

Напишите функцию, которая создает диагональную матрицу NхN с квадратами чисел от N до 1 на главной диагонали

In [109]:
def make_diag_matrix_by_N(N):
    """
    Inputs:
    число N < 100
    
    Outputs:
    матрица размера N*N с квадратами чисел от N до 1 на главной диагонали
    """
    
    matrix = np.eye(N) * np.arange(N, 0, -1) ** 2
#     1 0 0 0 0 * N, n-1, n-2. .. 1
#     0 1 0 0 0 * N, n-1, n-2
    return matrix

In [110]:
make_diag_matrix_by_N(10)

array([[100.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  81.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,  49.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,  36.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,  25.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,  16.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   4.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.]])

### Операция dot - умножение матрицы на вектор, и матрицы на матрицу

In [111]:
# два скаляра - умножение чисел
A = 2
B = 3

print(np.dot(A, B))

6


In [112]:
# скаляр и вектор - умножение вектора на скаляр
A = np.array([2., 3., 4.])
B = 3

print(np.dot(A, B))

[ 6.  9. 12.]


In [113]:
# два вектора - скалярное произведение
A = np.array([2., 3., 4.])
B = np.array([-2., 1., -1.])

print(np.dot(A, B))

-5.0


In [114]:
# матрица и вектор - умножение матрицы на вектор 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.ones(3)

print(np.dot(A, B))

[ 6. 15. 24.]


In [115]:
# если наоборот, то результат - умножение транспонированной матрицы на этот вектор
print(np.dot(B, A))
print(np.dot(A.T, B))

[12. 15. 18.]
[12. 15. 18.]


In [116]:
# две матрицы
A = np.ones((5, 6))
B = np.ones((6, 7))

print(np.dot(A, B))

[[6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]]


In [117]:
# важно, чтобы матрицы соответствовали по размеру (число столбцов первой матрицы равнялось число строк второй)
print(np.dot(B, A))

ValueError: shapes (6,7) and (5,6) not aligned: 7 (dim 1) != 5 (dim 0)

In [118]:
# другой способ перемножения матриц - операция matmul @
A = np.ones((5, 6))
B = np.ones((6, 7))

print(A @ B)

[[6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6. 6.]]


In [119]:
# тоже работает только для подходящих по размеру матриц
print(B @ A)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 7)

**Задача 6**

В бизнес-центре есть помещения разных типов. Помещения имеют разные параметры, эти параметры перечислены в списке features_names. Сами параметры помещений описаны в матрице rooms.

Помещения принадлежат препринимателям, которые сдают их в аренду. Каждый предприниматель владеет разным количеством помещений разного типа. То, сколькими помещениями каждого типа владеют предприниматели, описано в матрице owners.

Найдите указанные ниже значения

In [120]:
features_names = ['длина комнаты (м)', 'ширина комнаты (м)', 'этаж', 'год последнего ремонта', 'цена аренды (рубли)']

rooms = np.array([
    [3, 7, 8, 2001, 15000],
    [6, 8, 1, 2015, 36000],
    [5, 20, 7, 2012, 57000],
    [5, 8, 15, 2021, 41000],
    [2, 5, 1, 1999, 11000]
])

owners = np.array([
    [1, 3, 5, 1, 0],
    [0, 2, 0, 10, 0],
    [1, 1, 1, 1, 1]
])

# найдите среднюю цену аренды помещения
average_cost = np.sum(rooms[:, 4]) / rooms.shape[0]
print(average_cost)

32000.0


In [127]:
rooms_count = np.array([np.sum(x) for x in owners.T])
print(rooms_count)
average_cost = np.dot(rooms_count, rooms[:, -1]) / np.sum(rooms_count)
print(average_cost)

[ 2  6  6 12  1]
40407.40740740741


In [129]:
rooms_count = np.sum(owners, axis=0)
rooms_count

array([ 2,  6,  6, 12,  1])

In [121]:
# найдите суммарную цену, которую зарабатывает 1ый предприниматель, сдавая свои помещения
owner1_income = np.sum(rooms[:, 4] * owners[0])

print(owner1_income)

449000


In [122]:
np.dot(owners[0], rooms[:, 4])

449000

In [123]:
# найдите суммарную цену, которую зарабатывает каждый преприниматель, сдавая свои помещения
owners_income = np.dot(owners, rooms[:, 4])
owners_income

array([449000, 482000, 160000])

In [126]:
# посчитайте дополнительные фичи
# площадь помещения
area = rooms[:, 0] * rooms[:, 1]

# возраст ремонта
repair_old = 2022 - rooms[:, 3]

# бинарный признак "этаж 1 или не первый"
is_first_floor = (rooms[:, 2] == 1).astype('int')
is_first_floor

array([0, 1, 0, 0, 1])

### Обратная матрица и определитель

In [131]:
# определитель
A = np.eye(10)

print(A)
print(np.linalg.det(A))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
1.0


In [135]:
a = np.eye(3) * np.arange(1, 4)
print(a)
print(np.linalg.det(a))

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
6.0


In [ ]:
# a = diag(a1, a2, a3... an)
# det(a) = a1 * a2 * a3

In [136]:
B = 5 * np.eye(6) + np.ones(6)

print(B)
print(np.linalg.det(B.astype('int')))

# LU - разложение A = LU

[[6. 1. 1. 1. 1. 1.]
 [1. 6. 1. 1. 1. 1.]
 [1. 1. 6. 1. 1. 1.]
 [1. 1. 1. 6. 1. 1.]
 [1. 1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 1. 6.]]
34374.99999999999


In [138]:
# обратная матрица
A = np.array([[1, 2], [3, 4]])
B = np.linalg.inv(A)

print(B)

# B - обратная для A AB = BA = E

print(A @ B)

print (A @ B == np.eye(2))

print(np.allclose(A @ B, np.eye(2)))

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
[[ True  True]
 [False False]]
True


**Задача 5**

Решите задачу 5 из теста к лекции методами numpy. Транспонируйте матрицу $X$ и вычислите определитель получившейся матрицы.
$$X = \begin{pmatrix} 3 & -1 & 0 \\  2 & 1 & -1 \\  1 & 5 & 4 \end{pmatrix}$$

In [143]:
x = np.array([[3, -1, 0], [2, 1, -1], [1, 5, 4]])
x = x.transpose()
print(x)
print(np.linalg.det(x))

[[ 3  2  1]
 [-1  1  5]
 [ 0 -1  4]]
36.0


**Задача 6**

Решите задачу 6 из теста к лекции методами numpy. Найдите все обратимые матрицы из списка:

$$X = \begin{pmatrix} 3 & -1 & 0 \\ 2 & 1 & -1 \\ 1 & 5 & 4 \end{pmatrix}$$

$$Y = \begin{pmatrix} 3 & 0 & 0 \\ 1 & 0 & 4 \\ 5 & 6 & 4 \\ 3 & 3 & 6\\ \end{pmatrix}$$

$$M = \begin{pmatrix} 4 &  2 \\ 6 & 3  \end{pmatrix}$$

$$N = \begin{pmatrix} 0 & -1 \\ 1 & 0 \end{pmatrix}$$

In [144]:
y = np.array([[3, 0, 0], [1, 0, 4], [5, 6, 4], [3, 3, 6]])
m = np.array([[4, 2], [6, 3]])
n = np.array([[0, -1], [1, 0]])
matrixes = [x, y, m, n]

for matrix in matrixes:
    if matrix.shape[0] == matrix.shape[1] and np.linalg.det(matrix):
        print(matrix)

[[ 3  2  1]
 [-1  1  5]
 [ 0 -1  4]]
[[ 0 -1]
 [ 1  0]]
